const express = require('express')
const router = express.Router()
const routeUsers = require('./users')
const routeAppointments = require('./appointments')
const routeVouchers = require('./vouchers')
const routeAds = require('./ads')
const routeArticles = require('./articles')
const routeDrivers = require('./drivers')
const routeServices = require('./services')
const routeAdminSellers = require('./adminSellers')
const routeAdminMechanics = require('./adminMechanics')
const routeSuperAdmins = require('./superAdmins')
const routeProductCategories = require('./productCategories')
const routeProductTypes = require('./productTypes')
const routeProducts = require('./products')
const routeTransactions = require('./transactions')
const routeOrders = require('./orders')

router.use('/users', routeUsers)
router.use('/appointments', routeAppointments)
router.use('/vouchers', routeVouchers)
router.use('/ads', routeAds)
router.use('/articles', routeArticles)
router.use('/drivers', routeDrivers)
router.use('/services', routeServices)
router.use('/admin-sellers', routeAdminSellers)
router.use('/admin-mechanics', routeAdminMechanics)
router.use('/super-admins', routeSuperAdmins)
router.use('/product-categories', routeProductCategories)
router.use('/product-types', routeProductTypes)
router.use('/products', routeProducts)
router.use('/transactions', routeTransactions)
router.use('/orders', routeOrders)

module.exports = router
